name: Run specs

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run specs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Run specs
      run: bundle exec rspec
      env:
        DESTINY_API_KEY: ${{ vars.DESTINY_API_KEY }}
        DESTINY_OAUTH_CLIENT_ID: ${{ vars.DESTINY_OAUTH_CLIENT_ID }}
