name: Run rspec tests

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: "Run specs"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
    - name: Run specs
      run: |
        bundle install
        bundle exec rspec
      env:
        DESTINY_API_KEY: ${{ vars.DESTINY_API_KEY }}
